addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.12.0")
addSbtPlugin("org.scala-js"   % "sbt-scalajs"         % "1.22.0")
//addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.21.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
// addSbtPlugin("org.typelevel"       % "sbt-tpolecat"             % "0.6.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"  % "0.3.1")
addSbtPlugin("com.eed3si9n"        % "sbt-assembly" % "2.5.0")
