addSbtPlugin("com.github.sbt"     % "sbt-native-packager"      % "1.9.11")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.16.0")
//addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.21.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.typelevel"       % "sbt-tpolecat" % "0.5.0")
addSbtPlugin("com.github.reibitto" % "sbt-welcome"  % "0.3.1")
addSbtPlugin("com.eed3si9n" % "sbt-assembly" % "2.3.0")